site:
  name: QYep
  site: 'https://www.qingtaors.top'

# Default SEO metadata
metadata:
  title:
    default: QYep
    template: '%s — QYep'
  description: 'My devlog: project progress, problems, and solutions.'

googleSiteVerificationId: null

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      permalink: '/blog/%slug%'
    list:
      pathname: 'blog'
    category:
      pathname: 'category'
    tag:
      pathname: 'tag'
tag:
  robots:
    index: false

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

analytics:
  vendors:
    googleAnalytics:
      id: 'G-QQ7RLT57HJ'
